external: false
size: 10Gi

users:
  user1:
    password: strongpassword
  user2:
    password: hackme
  airflow:
    password: qwerty123
  debezium:
    replication: true

databases:

  myapp:
    roles:
      admin:
      - user1
      - debezium
      readonly:
      - user2

  airflow:
    roles:
      admin:
      - airflow
    extensions:
    - hstore

backup:
  enabled: false
  s3Region: us-east-1
  s3Bucket: s3.example.org/postgres-backups
  schedule: "0 2 * * *"
  cleanupStrategy: "--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
  s3AccessKey: oobaiRus9pah8PhohL1ThaeTa4UVa7gu
  s3SecretKey: ju3eum4dekeich9ahM1te8waeGai0oog
  resticPassword: ChaXoveekoh6eigh4siesheeda2quai0
