storage:
  storageClass: linstor-lvm
  size: 10Gi

primaryService:
  ipPool: private-ips
  ipAddress: 10.100.255.10

secondaryService:
  ipPool: private-ips
  ipAddress: 10.100.255.11

users:
  user1:
    password: strongpassword
  user2:
    password: hackme
  airflow:
    password: qwerty123
  debezium:
    replication: true

databases:

  myapp:
    roles:
      admin:
      - user1
      - debezium
      readonly:
      - user2

  airflow:
    roles:
      admin:
      - airflow
    extensions:
    - hstore
