host: ""

metricsStorages:
- name: shortterm
  retentionPeriod: "3d"
  deduplicationInterval: "5m"
  storage: 10Gi
- name: longterm
  retentionPeriod: "14d"
  deduplicationInterval: "15s"
  storage: 10Gi

oncall:
  enabled: false
