---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  {{- range $name, $u := .Values.users }}
  {{ $name }}-password: {{ $u.password }}
  {{- end }}
  {{- if not (and .Values.users.root .Values.users.root.password) }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Release.Name }}
  {{- if and $existingSecret (index $existingSecret.data "root-password") }}
  root-password: {{ index $existingSecret.data "root-password" }}
  {{- else }}
  root-password: {{ randAlphaNum 10 }}
  {{- end }}
  {{- end }}
