_helm:
  name: monitoring
  namespace: cozy-monitoring
  createNamespace: true
  privilegedNamespace: true
  dependsOn:
  - name: victoria-metrics-operator

metrics-server:
  defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    - --kubelet-insecure-tls

  metrics:
    enabled: true
  
  serviceMonitor:
    enabled: true
