apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpn
type: Opaque
stringData:
  shadowbox_server_config.json: |
    {
      "rollouts": [
        {
          "id": "single-port",
          "enabled": true
        }
      ],
      "portForNewAccessKeys": 40000,
      "hostname": "localhost"
    }
  shadowbox_config.json: |
    {
      "accessKeys": [
        {
          "id": "1",
          "metricsId": "f33f7fbf-6750-485c-9ac0-2ec261b5aa03",
          "name": "",
          "password": "UhrU93bi2eBORvo4dwxsEw",
          "port": 40000,
          "encryptionMethod": "chacha20-ietf-poly1305"
        },
        {
          "id": "2",
          "metricsId": "aa72b1f0-f48c-49e2-b153-2fb8817e4b54",
          "name": "sssss",
          "password": "7IhWAD1GzaNjLCMyG0LVhK",
          "port": 40000,
          "encryptionMethod": "chacha20-ietf-poly1305"
        },
        {
          "id": "3",
          "metricsId": "aa72b1f0-f48c-49e2-b153-2fb8817e4b54",
          "name": "foobar",
          "password": "aaaaaaaaaaaaaaaaaaaaaa",
          "port": 40000,
          "encryptionMethod": "chacha20-ietf-poly1305"
        },
        {
          "id": "4",
          "metricsId": "703c05a9-e4cd-4af2-a7ec-41906525c512",
          "name": "kvaps",
          "password": "asdasdASD",
          "port": 40000,
          "encryptionMethod": "chacha20-ietf-poly1305"
        }
      ],
      "nextId": 5
    }
