apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-admin-password
  namespace: 
data:
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-grafana-admin-password" .Release.Name) }}
  {{- if $existingSecret }}
  user: {{ index $existingSecret.data "user" }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  user: {{ b64enc "admin" }}
  password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
