apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: grafana-db
spec:
  rootPasswordSecretKeyRef:
    name: grafana-db
    key: root-password

  database: grafana-db
  username: grafana
  passwordSecretKeyRef:
    name: grafana-db
    key: password

  image: "mariadb:11.0.3"

  port: 3306

  replicas: 3
     
  replication:
    enabled: true

  #galera:
  #  enabled: true
  #  recovery:
  #    enabled: true
  #    clusterHealthyTimeout: 5m
  #    clusterBootstrapTimeout: 10m
  #    podRecoveryTimeout: 5m
  #    podSyncTimeout: 10m
  #  #primary:
  #  # automaticFailover: true
  #  # podIndex: 0

  podSecurityContext:
    runAsUser: 0

  volumeClaimTemplate:
    resources:
      requests:
        storage: 30Gi #-- depends on https://github.com/mariadb-operator/mariadb-operator/issues/262
    accessModes:
      - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db
stringData:
  password: oohaNgaph1kaeTaebooh
  root-password: hoh3Eif9shev5sei0oo6
