external: false
size: 10Gi

replicas: 2

users:
  root:
    password: strongpassword
  user1:
    privileges: ['ALL']
    maxUserConnections: 1000
    password: hackme
  user2:
    privileges: ['SELECT']
    maxUserConnections: 1000
    password: hackme

databases:
- wordpress1
- wordpress2
- wordpress3
- wordpress4

backup:
  enabled: false
  s3Region: us-east-1
  s3Bucket: s3.example.org/postgres-backups
  schedule: "0 2 * * *"
  cleanupStrategy: "--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
  s3AccessKey: oobaiRus9pah8PhohL1ThaeTa4UVa7gu
  s3SecretKey: ju3eum4dekeich9ahM1te8waeGai0oog
  resticPassword: ChaXoveekoh6eigh4siesheeda2quai0
