---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vminsert-vmcluster
  namespace: cozy-monitoring-hub
spec:
  endpoints:
  - path: /metrics
    port: http
    relabelConfigs:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster
      app.kubernetes.io/name: vminsert
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmselect-vmcluster
  namespace: cozy-monitoring
spec:
  endpoints:
  - path: /metrics
    port: http
    relabelConfigs:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster
      app.kubernetes.io/name: vmselect
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmstorage-vmcluster
  namespace: cozy-monitoring
spec:
  endpoints:
  - path: /metrics
    port: http
    relabelConfigs:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster
      app.kubernetes.io/name: vmstorage
