---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    auth.gitlab:
        name: Gitlab
        enabled: "true"
        allow_sign_up: "true"
        auto_login: "false"
        client_id: e03e8bbe-1a4f-4555-906e-710f1b148d7b
        client_secret: d57d2398-ce98-4309-a799-ac6d7cf54367
        scopes: api
        auth_url: "https://git.example.org/oauth/authorize"
        token_url: "https://git.example.org/oauth/token"
        api_url: "https://git.example.org/api/v4"
        #allowed_groups: '["cluster-admins"]'
        role_attribute_path: "contains(info.groups_direct[*], 'grafana-admin') && 'Admin' || contains(info.groups_direct[*], 'grafana-editor') && 'Editor' || 'Viewer'"
        #role_attribute_path: "is_admin && 'Admin' || 'Viewer'"
        #tls_skip_verify_insecure: "false"
        #use_pkce: "true"
        #use_refresh_token: "true"
    database:
      type: postgres
      name: ${GF_DATABASE_NAME}
      host: ${GF_DATABASE_HOST}
      user: ${GF_DATABASE_USER}
      password: ${GF_DATABASE_PASSWORD}
      #ssl_mode: require
    server:
      root_url: https://grafana.example.org
    security:
      admin_user: root
      admin_password: {{ .Values.adminPassword }}
  deployment:
    spec:
      replicas: 2
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:10.1.0
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
              readinessProbe:
                failureThreshold: 3
              env:
              - name: GF_INSTALL_PLUGINS
                value: grafana-worldmap-panel,flant-statusmap-panel,grafana-oncall-app,natel-discrete-panel
              - name: ONCALL_API_URL
                value: http://grafana-oncall-engine:8080
              - name: GF_DATABASE_HOST
                value: "grafana-db-rw:5432"
              - name: GF_DATABASE_PASSWORD
                valueFrom: { secretKeyRef: { name: grafana-db-app, key: password } }
              - name: GF_DATABASE_NAME
                value: "app"
              - name: GF_DATABASE_USER
                value: "app"
  ingress:
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
    spec:
      ingressClassName: nginx
      rules:
        - host: grafana.example.org
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
      - hosts:
        - grafana.example.org
        secretName: grafana-ingressmyingress-tls
