---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-lb
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.primaryService.ipPool }}
    metallb.universe.tf/ip-allocated-from-pool: {{ .Values.primaryService.ipPool }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.primaryService.ipAddress }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: redis-failover
    redisfailovers-role: master
  ports:
  - name: redis
    port: 6379
    targetPort: redis
