---
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  driver: etcd
  endpoints:
  - etcd-0.etcd-headless.{{ .Release.Namespace }}.svc:2379
  - etcd-1.etcd-headless.{{ .Release.Namespace }}.svc:2379
  - etcd-2.etcd-headless.{{ .Release.Namespace }}.svc:2379
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: etcd-ca-tls
          namespace: {{ .Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: etcd-ca-tls
          namespace: {{ .Release.Namespace }}
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: etcd-client-tls
          namespace: {{ .Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: etcd-client-tls
          namespace: {{ .Release.Namespace }}
