_helm:
  name: piraeus-operator
  namespace: cozy-linstor # must be same namespace as linstor
  createNamespace: true
  privilegedNamespace: false
  crds: CreateReplace
  dependsOn:
  - name: cert-manager

piraeus:
  installCRDs: true
  autogenerate: false
  tls:
    certManagerIssuerRef:
      name: ca-bootstrapper
      kind: Issuer
