{{- $cozyConfig := lookup "v1" "ConfigMap" "cozy-system" "cozystack" }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: cozy-monitoring
spec:
  externalLabels:
    cluster: cozystack
  extraArgs:
    promscrape.streamParse: "true"
  remoteWrite:
  {{- range $k, $v := $cozyConfig.data }}
  {{- if hasPrefix "monitoring-remote-write-url" $k }}
  - url: "{{ $v }}"
  {{- end }}
  {{- end }}
  scrapeInterval: 30s
  selectAllByDefault: true
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  #statefulMode: true
  #statefulStorage:
  #  volumeClaimTemplate:
  #    spec:
  #      resources:
  #          requests:
  #            storage: 20Gi
