{{- range $topic := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "{{ $.Release.Name }}-{{ kebabcase $topic.name }}"
  labels:
    strimzi.io/cluster: "{{ $.Release.Name }}"
spec:
  topicName: "{{ $topic.name }}"
  partitions: 10
  replicas: 3
  {{- with $topic.config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
