{{- if .Values.ownEtcd }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: {{ include "tenant.name" . }}
  labels:
    cozystack.io/ui: "true"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  chart:
    spec:
      chart: cozy-etcd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
      version: 1.0.0
  interval: 1m0s
  timeout: 5m0s
{{- end }}
