apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: {{ .Release.Namespace }}
spec:
  driver: etcd
  endpoints:
  - {{ .Release.Name }}-0.{{ .Release.Name }}.{{ .Release.Namespace }}.svc:2379
  - {{ .Release.Name }}-1.{{ .Release.Name }}.{{ .Release.Namespace }}.svc:2379
  - {{ .Release.Name }}-2.{{ .Release.Name }}.{{ .Release.Namespace }}.svc:2379
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: ca.crt
          name: {{ .Release.Name }}-certs
          namespace: {{ .Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: ca.key
          name: {{ .Release.Name }}-certs
          namespace: {{ .Release.Namespace }}
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: {{ .Release.Name }}-root-client-certs
          namespace: {{ .Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: {{ .Release.Name }}-root-client-certs
          namespace: {{ .Release.Namespace }}
