---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-secondary-haproxy
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # TODO
  # There is an issue with 'externalTraficPolicy: Local' and VMs accessing externalIP services from
  # internal network, trafic is not routed due to fact their hipervisor have no local workload running
  # Current workaround that all the nodes of parnet cluster must have at least one replica per node
  # which are running the virtual machnes of child cluster.
  # Consider moving to KubeVirt so all local VMs will get local identities, so internalTrafficPolicy will
  # considered for them instead of externalTraficPolicy
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-secondary-haproxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-secondary-haproxy
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/haproxy/configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - mariadb
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}-secondary-haproxy
              topologyKey: kubernetes.io/hostname
      containers:
      - image: haproxy:latest
        name: haproxy
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy
          name: config
      volumes:
      - configMap:
          name: {{ .Release.Name }}-secondary-haproxy
        name: config
