---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secondary-haproxy
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.secondaryService2.ipPool }}
    metallb.universe.tf/ip-allocated-from-pool: {{ .Values.secondaryService2.ipPool }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.secondaryService2.ipAddress }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  selector:
    app: {{ .Release.Name }}-secondary-haproxy
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: mysql
