---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.loadBalancerIP }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ . }}
  {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  selector:
    app: {{ .Release.Name }}-haproxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
