{{- $myNS := lookup "v1" "Namespace" "" .Release.Namespace }}
{{- $ingress := index $myNS.metadata.annotations "namespace.cozystack.io/ingress" }}
{{- $host := index $myNS.metadata.annotations "namespace.cozystack.io/host" }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-system
spec:
  chart:
    spec:
      chart: cozy-seaweedfs
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  values:
    seaweedfs:
      
      volume:
        replicas: {{ .Values.replicas }}
      
        dataDirs:
        - name: data1
          type: "persistentVolumeClaim"
          size: "{{ .Values.size }}"
          maxVolumes: 0
      
      s3:
        ingress:
          className: {{ $ingress }}
          host: {{ .Values.host | default (printf "%s.%s" .Release.Name $host) }}
