{{- $cozyConfig := lookup "v1" "ConfigMap" "cozy-system" "cozystack" }}
{{- range $k, $v := $cozyConfig.data }}
{{- if hasPrefix "ipv4-external-pool-" $k }}
{{- $name := trimPrefix "ipv4-external-pool-" $k }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cozy-{{ $name }}
spec:
  #autoAssign: false
  addresses:
    {{- range (splitList "," $v) }}
    - {{ . }}
    {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cozy-{{ $name }}
spec:
  ipAddressPools:
  - cozy-{{ $name }}
{{- end }}
{{- end }}
