{{- if .Values.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-write
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  ports:
  - name: postgres
    port: 5432
  selector:
    cnpg.io/cluster: {{ .Release.Name }}
    role: primary
{{- end }}
