---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    namespace.cozystack.io/etcd: tenant-root
    namespace.cozystack.io/monitoring: tenant-root
    namespace.cozystack.io/ingress: tenant-root
  name: tenant-root
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-root
  namespace: tenant-root
  labels:
    cozystack.io/ui: "true"
spec:
  interval: 1m
  releaseName: tenant-root
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
