---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: root
  namespace: tenant-root
  labels:
    cozystack.io/ui: "true"
spec:
  interval: 1m
  releaseName: root
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
