apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cozy-cilium
spec:
  interval: 1m
  releaseName: cilium
  chart:
    spec:
      chart: cozy-cilium
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeovn
  namespace: cozy-kubeovn
spec:
  interval: 1m
  releaseName: kubeovn
  chart:
    spec:
      chart: cozy-kubeovn
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  values:
    cozystack:
      configHash: {{ index (lookup "v1" "ConfigMap" "cozy-system" "cozystack") "data" | toJson | sha256sum }}
      nodesHash: {{ include "master.nodeIPs" . | sha256sum }}
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cozy-fluxcd
  namespace: cozy-fluxcd
spec:
  interval: 1m
  releaseName: fluxcd
  chart:
    spec:
      chart: cozy-fluxcd
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cozy-cert-manager
spec:
  interval: 1m
  releaseName: cert-manager
  chart:
    spec:
      chart: cozy-cert-manager
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: cozy-cert-manager
spec:
  interval: 1m
  releaseName: cert-manager-issuers
  chart:
    spec:
      chart: cozy-cert-manager-issuers
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: cozy-victoria-metrics-operator
spec:
  interval: 1m
  releaseName: victoria-metrics-operator
  chart:
    spec:
      chart: cozy-victoria-metrics-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: cozy-monitoring
spec:
  interval: 1m
  releaseName: monitoring
  chart:
    spec:
      chart: cozy-monitoring
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: victoria-metrics-operator
    namespace: cozy-victoria-metrics-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevirt-operator
  namespace: cozy-kubevirt
spec:
  interval: 1m
  releaseName: kubevirt-operator
  chart:
    spec:
      chart: cozy-kubevirt-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevirt
  namespace: cozy-kubevirt
spec:
  interval: 1m
  releaseName: kubevirt
  chart:
    spec:
      chart: cozy-kubevirt
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: kubevirt-operator
    namespace: cozy-kubevirt
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: cozy-metallb
spec:
  interval: 1m
  releaseName: metallb
  chart:
    spec:
      chart: cozy-metallb
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: cozy-grafana-operator
spec:
  interval: 1m
  releaseName: grafana-operator
  chart:
    spec:
      chart: cozy-grafana-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: cozy-mariadb-operator
spec:
  interval: 1m
  releaseName: mariadb-operator
  chart:
    spec:
      chart: cozy-mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
  - name: victoria-metrics-operator
    namespace: cozy-victoria-metrics-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: cozy-postgres-operator
spec:
  interval: 1m
  releaseName: postgres-operator
  chart:
    spec:
      chart: cozy-postgres-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: cozy-rabbitmq-operator
spec:
  interval: 1m
  releaseName: rabbitmq-operator
  chart:
    spec:
      chart: cozy-rabbitmq-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: cozy-redis-operator
spec:
  interval: 1m
  releaseName: redis-operator
  chart:
    spec:
      chart: cozy-redis-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piraeus-operator
  namespace: cozy-linstor
spec:
  interval: 1m
  releaseName: piraeus-operator
  chart:
    spec:
      chart: cozy-piraeus-operator
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linstor
  namespace: cozy-linstor
spec:
  interval: 1m
  releaseName: linstor
  chart:
    spec:
      chart: cozy-linstor
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: piraeus-operator
    namespace: cozy-linstor
  - name: cert-manager
    namespace: cozy-cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telepresence
  namespace: cozy-telepresence
spec:
  interval: 1m
  releaseName: traffic-manager
  chart:
    spec:
      chart: cozy-telepresence
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: cozy-ingress-nginx
spec:
  interval: 1m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: cozy-ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: cozy-kubeapps
spec:
  interval: 1m
  releaseName: kubeapps
  chart:
    spec:
      chart: cozy-kubeapps
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
