apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cozy-fluxcd
  namespace: cozy-fluxcd
spec:
  interval: 1m0s
  ref:
    branch: mvp
  secretRef:
    name: flux-system
  timeout: 60s
  url: ssh://git@github.com/aenix-io/cozystack
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeovn
  namespace: cozy-kubeovn
spec:
  interval: 1m
  releaseName: kubeovn
  chart:
    spec:
      chart: system/kubeovn
      sourceRef:
        kind: GitRepository
        name: cozy-fluxcd
        namespace: cozy-fluxcd
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cozy-cilium
spec:
  interval: 1m
  releaseName: cilium
  chart:
    spec:
      chart: system/cilium
      sourceRef:
        kind: GitRepository
        name: cozy-fluxcd
        namespace: cozy-fluxcd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: cozy-telepresence
spec:
  interval: 1m
  releaseName: traffic-manager
  chart:
    spec:
      chart: system/telepresence
      sourceRef:
        kind: GitRepository
        name: cozy-fluxcd
        namespace: cozy-fluxcd
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
